# Generated by Django 2.0.6 on 2018-06-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('isbn10', models.CharField(max_length=10)),
                ('isbn13', models.CharField(max_length=13)),
                ('book_type', models.CharField(max_length=45)),
                ('publisher', models.CharField(max_length=45)),
                ('author', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('publication_at', models.DateField(blank=True,
                                                    null=True)),
                ('registration_at', models.DateTimeField(auto_now_add=True)),
                ('book_writing', models.TextField(blank=True)),
                ('book_contents', models.TextField(blank=True)),
                ('star_point', models.PositiveSmallIntegerField(blank=True,
                                                                null=True)),
                ('author_writing', models.TextField(blank=True)),
                ('book', models.OneToOneField(on_delete=True,
                                              to='books.Book')),
            ],
        ),
    ]
