# Generated by Django 2.0.6 on 2018-06-12 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('rental_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('return_standby', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=True,
                                              to='books.Book')),
                ('lender', models.ForeignKey(on_delete=True,
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
